

server:
  port: ${ENV_PORT}

scope: ${ENV_SCOPE}

spring:
  datasource:
    url: ${ENV_DB_URL:jdbc:h2:mem:testdb}
    driverClassName: ${ENV_DB_CLASS}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect